# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo', '0002_localidad_departamento'),
        ('candidatos', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('minuta', models.TextField(blank=True, help_text='Qué se dijo/mostró?')),
                ('candidatos', models.ManyToManyField(related_name='apariciones_en_medios', to='candidatos.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='DatoDeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'email'), ('teléfono', 'teléfono'), ('web', 'web'), ('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('skype', 'skype')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del medio')),
                ('tipo', models.CharField(choices=[('RADIO', 'RADIO'), ('TELEVISION', 'TELEVISION'), ('GRAGICA', 'GRAGICA'), ('VIA PUBLICA', 'VIA PUBLICA'), ('PORTAL WEB', 'PORTAL WEB'), ('REDES SOCIALES', 'REDES SOCIALES')], max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('detalles_tecnicos', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=50)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('relacion', models.CharField(choices=[('AMIGX', 'AMIGX'), ('COMPAÑERX', 'COMPAÑERX'), ('INDIFERENTE', 'INDIFERENTE'), ('OPOSITXR', 'OPOSITXR')], max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=50)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del programa o sección')),
                ('detalles', models.TextField(blank=True, help_text='Dias, horarios, comentarios, etc')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.Medio')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, choices=[('Conductor/a', 'Conductor/a'), ('Periodista', 'Periodista'), ('Productor/a', 'Productor/a'), ('Técnico/a', 'Técnico/a'), ('Contacto', 'Contacto')], max_length=50)),
                ('es_contacto', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.Persona')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='programa',
            name='staff',
            field=models.ManyToManyField(related_name='programas_realizados', through='prensa.Rol', to='prensa.Persona'),
        ),
        migrations.AddField(
            model_name='aparicion',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prensa.Programa'),
        ),
        migrations.AddField(
            model_name='aparicion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Palabras clave separadas por coma. Ejemplo: entrevista, trayectoria, lucha gremial', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
