# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datodecontacto',
            unique_together=set([]),
        ),
    ]
