# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('prensa', '0002_auto_20170717_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Localidad'),
        ),
    ]
