# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0002_auto_20170719_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='fuente',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
