# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prensa', '0003_persona_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datodecontacto',
            name='tipo',
            field=models.CharField(choices=[('email', 'email'), ('teléfono', 'teléfono'), ('web', 'web'), ('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('skype', 'skype')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datodecontacto',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
