# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prensa', '0005_auto_20170804_0103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datodecontacto',
            unique_together=set([('tipo', 'valor', 'content_type', 'object_id')]),
        ),
    ]
