# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0002_auto_20170801_1241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionFiscalDeMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ingreso', models.DateTimeField(editable=False, null=True)),
                ('egreso', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionFiscalGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ingreso', models.DateTimeField(editable=False, null=True)),
                ('egreso', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('de_mesa', 'de Mesa')], max_length=20)),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('tipo_dni', models.CharField(choices=[('DNI, CI, LE, LC', 'DNI, CI, LE, LC')], default='DNI', max_length=3)),
                ('dni', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Fiscales',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('referentes', models.ManyToManyField(related_name='referentes_de_la_orga', to='fiscales.Fiscal')),
            ],
        ),
        migrations.AddField(
            model_name='fiscal',
            name='organizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Organizacion'),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionfiscalgeneral',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
        ),
        migrations.AddField(
            model_name='asignacionfiscalgeneral',
            name='lugar_votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_general', to='elecciones.LugarVotacion'),
        ),
        migrations.AddField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
        ),
        migrations.AddField(
            model_name='asignacionfiscaldemesa',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_de_mesa', to='elecciones.Mesa'),
        ),
    ]
