# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='fiscal',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='localidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_mesa', to='fiscales.Fiscal'),
        ),
        migrations.AlterField(
            model_name='asignacionfiscaldemesa',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_fiscales', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='asignacionfiscalgeneral',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_escuela', to='fiscales.Fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Organizacion'),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='tipo_dni',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('LE', 'LE'), ('LC', 'LC')], default='DNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fiscal',
            unique_together=set([('tipo_dni', 'dni')]),
        ),
    ]
