# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0002_auto_20170801_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionfiscaldemesa',
            options={'verbose_name': 'Asignación de Fiscal de Mesa', 'verbose_name_plural': 'Asignaciones de Fiscal de Mesa'},
        ),
        migrations.AlterModelOptions(
            name='asignacionfiscalgeneral',
            options={'verbose_name': 'Asignación de Fiscal General', 'verbose_name_plural': 'Asignaciones de Fiscal General'},
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
    ]
