# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0004_auto_20170803_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='barrio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
