# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0006_auto_20170803_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='referentes',
            field=models.ManyToManyField(blank=True, related_name='es_referente_de', to='fiscales.Fiscal'),
        ),
    ]
