# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0008_auto_20170804_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_mesa', to='fiscales.Fiscal'),
        ),
        migrations.AlterField(
            model_name='asignacionfiscaldemesa',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='elecciones.Mesa'),
        ),
        migrations.AlterField(
            model_name='asignacionfiscalgeneral',
            name='lugar_votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='elecciones.LugarVotacion'),
        ),
    ]
