# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0012_auto_20170808_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='dni',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
