# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0013_auto_20170809_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionfiscaldemesa',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_mesa', to='fiscales.Fiscal'),
        ),
    ]
