# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0015_auto_20170813_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='estado',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='PRE-INSCRIPTO', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas internas, no se muestran'),
        ),
    ]
