# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0017_fiscal_escuela_donde_vota'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('mañana', 'mañana'), ('tarde', 'tarde'), ('todo el día', 'todo el día')], max_length=20),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='movilidad',
            field=models.NullBooleanField(help_text='Movilidad propia'),
        ),
    ]
