# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0018_auto_20170902_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
