# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0020_auto_20170901_0026'),
        ('fiscales', '0019_auto_20170903_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionfiscalgeneral',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
            preserve_default=False,
        ),
    ]
