# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0021_auto_20170904_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='escuela_donde_vota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.LugarVotacion', verbose_name='Escuela preferida para fiscalizar'),
        ),
    ]
