# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0022_auto_20170926_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionfiscalgeneral',
            name='eleccion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
        ),
    ]
