# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'verbose_name': 'Circuito electoral', 'verbose_name_plural': 'Circuitos electorales'},
        ),
        migrations.AlterModelOptions(
            name='lugarvotacion',
            options={'verbose_name': 'Lugar de votación', 'verbose_name_plural': 'Lugares de votación'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección electoral', 'verbose_name_plural': 'Secciones electorales'},
        ),
        migrations.AddField(
            model_name='lugarvotacion',
            name='geom',
            field=djgeojson.fields.PointField(null=True),
        ),
        migrations.AlterField(
            model_name='lugarvotacion',
            name='latitud',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lugarvotacion',
            name='longitud',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
