# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0003_auto_20170801_2355'),
        ('elecciones', '0002_auto_20170801_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votomesareportado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='EN ESPERA', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='hora_abierta',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['ABIERTA'])),
        ),
        migrations.AddField(
            model_name='mesa',
            name='hora_cerrada',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['CERRADA'])),
        ),
        migrations.AddField(
            model_name='mesa',
            name='hora_escrutada',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='estado', when=set(['ESCRUTADA'])),
        ),
        migrations.AddField(
            model_name='votomesareportado',
            name='fiscal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fiscales.Fiscal'),
            preserve_default=False,
        ),
    ]
