# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import elecciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_auto_20170803_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='dne_id',
        ),
        migrations.AddField(
            model_name='mesa',
            name='foto_del_acta',
            field=models.ImageField(blank=True, null=True, upload_to=elecciones.models.path_foto_acta),
        ),
        migrations.AddField(
            model_name='opcion',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden en el acta'),
            preserve_default=False,
        ),
    ]
