# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_auto_20170804_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(help_text='Orden opcion'),
        ),
    ]
