# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0008_auto_20170804_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='orden',
            field=models.PositiveIntegerField(default=99, help_text='Orden opcion'),
            preserve_default=False,
        ),
    ]
