# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0009_auto_20170804_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['orden'], 'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, help_text='Orden en la boleta', null=True),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Partido'),
        ),
        migrations.AlterField(
            model_name='votomesaoficial',
            name='votos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='votomesareportado',
            name='votos',
            field=models.PositiveIntegerField(),
        ),
    ]
