# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscales', '0010_auto_20170807_0041'),
        ('elecciones', '0010_auto_20170804_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='referentes',
            field=models.ManyToManyField(blank=True, related_name='es_referente_de_circuito', to='fiscales.Fiscal'),
        ),
    ]
