# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0012_mesa_es_testigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugarvotacion',
            name='geo',
        ),
    ]
