# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0015_auto_20170812_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='es_contable',
            field=models.BooleanField(default=True),
        ),
    ]
