# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0016_opcion_es_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='slug',
            field=models.SlugField(default='paso2017', unique=True),
            preserve_default=False,
        ),
    ]
