# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0017_eleccion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elecciones.Eleccion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='votomesaoficial',
            unique_together=set([('mesa', 'opcion')]),
        ),
        migrations.AlterUniqueTogether(
            name='votomesareportado',
            unique_together=set([('mesa', 'opcion')]),
        ),
        migrations.RemoveField(
            model_name='votomesaoficial',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='votomesareportado',
            name='eleccion',
        ),
    ]
