# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0019_auto_20170830_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
