# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0020_auto_20170901_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='codigo_dne',
            field=models.PositiveIntegerField(blank=True, help_text='Nº asignado en la base de datos de resultados oficiales', null=True),
        ),
    ]
