# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0021_auto_20171008_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarvotacion',
            name='circuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='elecciones.Circuito'),
        ),
    ]
