# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0024_auto_20171017_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='foto_del_acta',
        ),
        migrations.AddField(
            model_name='mesa',
            name='orden_de_carga',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
