# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0002_auto_20171014_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
