# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0004_attachment_problema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='foto',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='attachments/', width_field='width'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mimetype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='problema',
            field=models.CharField(blank=True, choices=[('acta repetida', 'acta repetida'), ('no es una foto válida', 'no es una foto válida'), ('no se entiende', 'no se entiende'), ('foto rotada', 'foto rotada')], max_length=100, null=True),
        ),
    ]
