# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('candidatura_a', models.CharField(choices=[('Diputado Nacional', 'Diputado Nacional'), ('Senador Nacional', 'Senador Nacional')], default='Diputado Nacional', max_length=50)),
                ('tipo', models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], max_length=20)),
                ('posicion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.Lista'),
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set([('lista', 'candidatura_a', 'posicion')]),
        ),
    ]
