# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('poblacion', models.PositiveIntegerField(verbose_name='Población')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('poblacion', models.PositiveIntegerField(verbose_name='Población')),
                ('tipo', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=50)),
            ],
        ),
    ]
